version: ${project.version}

database:
  #存储类型 SQLite、Mysql
  type: sqlite
  #以下参数为mysql配置
  mysql_ip: 127.0.0.1
  mysql_port: 3306
  mysql_username: root
  mysql_password: 123456
  mysql_database: "ctonlinetime"
  mysql_option: "useUnicode=true&characterEncoding=utf-8&useSSL=false"
  hikariCP:
    #数据库连接池配置，基本无需改动，如需改动请根据自身需要修改，谨慎修改可能会造成插件无法使用
    connectionTimeout: 30000
    #连接超时时间 默认值：30000（30秒）
    minimumIdle: 10
    #最小空闲连接数
    maximumPoolSize: 50
    #池允许达到的最大大小，包括空闲和正在使用的连接
Setting:
  #菜单中物品默认材质
  defaultItemType:
    type:
      name: 'minecraft:glass_bottle'
      #是否打开附魔  部分物品会出现问题，请提前测试
      enchantment: false
  #挂机相关配置
  afkConfig:
    #是否开启挂机检测 进入挂机状态之后将不记录在线时间
    use: false
    #挂机标准为多长时间无响应 单位:分钟
    time: 5
    #检测强度 default默认等级 strong加强等级  在strong模式下玩家只有视角动也被算作挂机 default模式下玩家xyz及视角改变任意一项就不算作挂机
    mode: default
    #挂机提醒
    message:
      joinAfk: '<red><bold>[在线奖励]</bold> 你已进入挂机模式,将不再记录在线时间!</red>'
      levelAfk: '<green><bold>[在线奖励]</bold> 你已离开挂机模式,开始记录在线时间!</green>'
  #公告提醒相关配置
  remind:
    #是否打开公告提醒
    use: true
    #提醒间隔时间  单位分钟
    time: 3
    # 使用 MiniMessage 格式，支持点击和悬停
    message: '<green><click:run_command:/cor><hover:show_text:"<yellow>点击打开菜单</yellow>">[在线奖励]有奖励可领取,点击领取</hover></click></green> <red><click:run_command:/cor remind off><hover:show_text:"<gray>关闭提醒</gray>">[点击关闭提醒]</hover></click></red>'
  #在线提醒配置
  onlineRemind:
    #是否打开在线提醒
    use: true
    remindValues:
      -
        OnlineTime: 10
        Message: '<green>你已经在线10分钟了，注意休息哦～</green>'
      -
        OnlineTime: 20
        Message: '<green>你已经在线20分钟了，适当游戏怡情，不要时间太长哦～</green>'
  #时间限制  记录在线时间的时间段配置
  timeLimit:
    #是否打开在线时间段配置
    use: false
    #时间限制  24小时制 如: 8 20 为早上八点到晚上八点记录在线时间  只能为整数  中间空格隔开
    limit: '8 20'
